services:
  app:
    image: node:20-alpine
    container_name: helo-luxury-air-dev
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - PORT=8080
    restart: unless-stopped 