services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helo-luxury-air
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 